name: 'okami-action'
description: 'Post an image of a cute animal straight to your PR'
inputs:
  okami-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  animal-type:
    description: 'What animal type image to post to the pull request'
    required: false
    default: 'shiba'
  update-image:
    description: 'Update a single comment each time this action is executed'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'gift'
  color: 'orange'