on:
  pull_request:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Job to test the action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Post step
        uses: ./ # Uses an action in the root directory
        with:
          okami-token: ${{ secrets.GITHUB_TOKEN }}
          # animal-type: "shiba"
