on:
  pull_request:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Job to test the action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Post Default
        uses: ./
        with:
          okami-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post shiba
        uses: ./
        with:
          okami-token: ${{ secrets.GITHUB_TOKEN }}
          animal-type: "shiba"

      - name: Post cat
        uses: ./
        with:
          okami-token: ${{ secrets.GITHUB_TOKEN }}
          animal-type: "cat"

      - name: Post bird
        uses: ./
        with:
          okami-token: ${{ secrets.GITHUB_TOKEN }}
          animal-type: "bird"

      - name: Post fox
        uses: ./
        with:
          okami-token: ${{ secrets.GITHUB_TOKEN }}
          animal-type: "fox"

      - name: Post dog
        uses: ./
        with:
          okami-token: ${{ secrets.GITHUB_TOKEN }}
          animal-type: "dog"
